/**
 * Deterministic feature verify scripts — no LLM, paired with prompt optimizer.
 */

export type FeatureVerifyScript = {
  id: string;
  label: string;
  command: string;
};

function normalizePath(p: string): string {
  return p.replace(/\\/g, "/").replace(/^\.\/+/, "");
}

function intentLabel(userIntent: string, max = 48): string {
  const t = userIntent.trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max - 1)}…`;
}

/** Build 1–3 executable verify commands from scoped paths + intent. */
export function buildFeatureVerifyScripts(
  userIntent: string,
  paths: readonly string[],
  packId: string
): FeatureVerifyScript[] {
  const normalized = paths.map(normalizePath);
  const joined = normalized.join(" ").toLowerCase();
  const prefix = packId.slice(0, 8);
  const scripts: FeatureVerifyScript[] = [];
  const intent = intentLabel(userIntent);

  if (
    joined.includes(".rb") ||
    joined.includes("gemfile") ||
    joined.includes("app/controllers") ||
    joined.includes("test/")
  ) {
    const testFile = normalized.find((p) => /test\/.*_test\.rb$/i.test(p));
    if (testFile) {
      scripts.push({
        id: `${prefix}-rails-file`,
        label: `Verify · ${testFile}`,
        command: `bundle exec rails test ${testFile}`,
      });
    }
    scripts.push({
      id: `${prefix}-rails-suite`,
      label: testFile ? "Rails full test suite" : `Verify · ${intent}`,
      command: "bundle exec rails test",
    });
  } else if (
    joined.includes(".ts") ||
    joined.includes(".tsx") ||
    joined.includes(".js") ||
    joined.includes(".jsx")
  ) {
    const specFile = normalized.find((p) =>
      /\.(test|spec)\.(ts|tsx|js|jsx)$/i.test(p)
    );
    if (specFile) {
      scripts.push({
        id: `${prefix}-npm-spec`,
        label: `Verify · ${specFile}`,
        command: `npm test -- ${specFile}`,
      });
    }
    scripts.push({
      id: `${prefix}-npm-test`,
      label: specFile ? "npm test (full)" : `Verify · ${intent}`,
      command: "npm test",
    });
    scripts.push({
      id: `${prefix}-npm-build`,
      label: "npm run build",
      command: "npm run build",
    });
  } else {
    scripts.push({
      id: `${prefix}-npm-test`,
      label: `Verify · ${intent}`,
      command: "npm test",
    });
    scripts.push({
      id: `${prefix}-npm-build`,
      label: "npm run build",
      command: "npm run build",
    });
  }

  const seen = new Set<string>();
  return scripts.filter((s) => {
    const key = s.command.trim();
    if (!key || seen.has(key)) return false;
    seen.add(key);
    return true;
  }).slice(0, 3);
}

export function formatVerifyShellScript(commands: readonly string[]): string {
  const body = commands.filter(Boolean).map((c) => c.trim());
  return [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "# MSGF auto-verify — generated by prompt optimizer (Run Scripts)",
    "",
    ...body,
    "",
  ].join("\n");
}

export function formatVerifyPowerShellScript(commands: readonly string[]): string {
  const body = commands.filter(Boolean).map((c) => c.trim());
  const lines = body.length ? body : ["npm test"];
  return [
    "# MSGF auto-verify — generated by prompt optimizer (Run Scripts)",
    "$ErrorActionPreference = 'Stop'",
    "",
    ...lines,
    "",
  ].join("\n");
}

export function formatRunScriptsMarkdownSection(scripts: readonly FeatureVerifyScript[]): string[] {
  if (!scripts.length) return [];
  return [
    "## Auto-verify (Run Scripts)",
    "",
    "These commands are registered in **MSGF Command Center → Run Scripts**:",
    "",
    ...scripts.map((s) => `- **${s.label}** — \`${s.command}\``),
    "",
    "After the agent implements the feature, click **Run Scripts** in the sidebar to verify without re-pasting context.",
    "",
  ];
}
