/**
 * @msgf-license-header
 * Proprietary and Confidential
 * Copyright (c) Elphie Syntax LLC. All Rights Reserved.
 *
 * This source code and associated documentation are the exclusive property of
 * Elphie Syntax LLC. Unauthorized copying, distribution, publication, or
 * reverse-engineering — including decompilation, disassembly, or derivative
 * works — is strictly prohibited without prior written consent.
 *
 * Distribution Build ID: MSGF-3a4c1de-20260529T200349Z-internal
 */
/**
 * Deterministic feature verify scripts — no LLM, paired with prompt optimizer.
 */

import {
  assertAllowedVerifyCommand,
  isSafeRepoRelativePath,
} from "@/lib/utils/shell-safe-path";

export type FeatureVerifyScript = {
  id: string;
  label: string;
  command: string;
};

function normalizePath(p: string): string {
  return p.replace(/\\/g, "/").replace(/^\.\/+/, "");
}

function intentLabel(userIntent: string, max = 48): string {
  const t = userIntent.trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max - 1)}…`;
}

/** Build 1–3 executable verify commands from scoped paths + intent. */
export function buildFeatureVerifyScripts(
  userIntent: string,
  paths: readonly string[],
  packId: string
): FeatureVerifyScript[] {
  const normalized = paths.map(normalizePath);
  const joined = normalized.join(" ").toLowerCase();
  const prefix = packId.slice(0, 8);
  const scripts: FeatureVerifyScript[] = [];
  const intent = intentLabel(userIntent);

  if (
    joined.includes(".rb") ||
    joined.includes("gemfile") ||
    joined.includes("app/controllers") ||
    joined.includes("test/")
  ) {
    const testFile = normalized.find((p) => /test\/.*_test\.rb$/i.test(p));
    if (testFile) {
      scripts.push({
        id: `${prefix}-rails-file`,
        label: `Verify · ${testFile}`,
        command: `bundle exec rails test ${testFile}`,
      });
    }
    scripts.push({
      id: `${prefix}-rails-suite`,
      label: testFile ? "Rails full test suite" : `Verify · ${intent}`,
      command: "bundle exec rails test",
    });
  } else if (
    joined.includes(".ts") ||
    joined.includes(".tsx") ||
    joined.includes(".js") ||
    joined.includes(".jsx")
  ) {
    const specFile = normalized.find((p) =>
      /\.(test|spec)\.(ts|tsx|js|jsx)$/i.test(p)
    );
    if (specFile) {
      scripts.push({
        id: `${prefix}-npm-spec`,
        label: `Verify · ${specFile}`,
        command: `npm test -- ${specFile}`,
      });
    }
    scripts.push({
      id: `${prefix}-npm-test`,
      label: specFile ? "npm test (full)" : `Verify · ${intent}`,
      command: "npm test",
    });
    scripts.push({
      id: `${prefix}-npm-build`,
      label: "npm run build",
      command: "npm run build",
    });
  } else {
    scripts.push({
      id: `${prefix}-npm-test`,
      label: `Verify · ${intent}`,
      command: "npm test",
    });
    scripts.push({
      id: `${prefix}-npm-build`,
      label: "npm run build",
      command: "npm run build",
    });
  }

  const seen = new Set<string>();
  return scripts
    .filter((s) => {
      const key = s.command.trim();
      if (!key || seen.has(key)) return false;
      try {
        assertAllowedVerifyCommand(key);
      } catch {
        return false;
      }
      seen.add(key);
      return true;
    })
    .slice(0, 3);
}

export function formatVerifyShellScript(commands: readonly string[]): string {
  const body = commands.filter(Boolean).map((c) => c.trim());
  return [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "# MSGF auto-verify — generated by prompt optimizer (Run Scripts)",
    "",
    ...body,
    "",
  ].join("\n");
}

export function formatVerifyPowerShellScript(commands: readonly string[]): string {
  const body = commands.filter(Boolean).map((c) => c.trim());
  const lines = body.length ? body : ["npm test"];
  return [
    "# MSGF auto-verify — generated by prompt optimizer (Run Scripts)",
    "$ErrorActionPreference = 'Stop'",
    "",
    ...lines,
    "",
  ].join("\n");
}

export function formatRunScriptsMarkdownSection(scripts: readonly FeatureVerifyScript[]): string[] {
  if (!scripts.length) return [];
  const primary = scripts[0]!.command;
  return [
    "## Auto-verify (Run Scripts)",
    "",
    "These commands are registered in **MSGF Command Center → Run Scripts**:",
    "",
    ...scripts.map((s) => `- **${s.label}** — \`${s.command}\``),
    "",
    `**Agent:** your work is not done until \`${primary}\` would pass locally.`,
    "**Operator:** after the agent finishes, click **Run Scripts** in the sidebar — no new prompt required.",
    "",
  ];
}

function stripMarkdownCommand(hint: string): string {
  return hint.replace(/`/g, "").trim();
}

/** Mandatory agent execution rules — MSGF V1 structured prompt block. */
export function formatAgentInstructionsSection(input: {
  userIntent: string;
  paths: readonly string[];
  verifyScripts: readonly FeatureVerifyScript[];
  verifyHint: string;
}): string[] {
  const primaryVerify =
    input.verifyScripts[0]?.command ?? stripMarkdownCommand(input.verifyHint);

  const testPaths = input.paths.filter((p) =>
    /test\/|\.(test|spec)\.(rb|ts|tsx|js|jsx)$/i.test(p)
  );
  const implPaths = input.paths.filter(
    (p) => !/test\/|\.(test|spec)\.(rb|ts|tsx|js|jsx)$/i.test(p)
  );

  const featureSurfaceHint =
    implPaths.length > 0
      ? implPaths.slice(0, 6).map((p) => `\`${p}\``).join(", ")
      : "the scoped production paths listed above";

  const existingTestHint =
    testPaths.length > 0
      ? testPaths.map((p) => `\`${p}\``).join(", ")
      : "a conventional test file mirroring the changed production path (e.g. `*_test.rb`, `*.test.ts`)";

  return [
    "### 📋 MANDATORY AGENT EXECUTION RULES",
    "",
    "**Composer setup:** Attach the **@** files/folders from this pack first — never paste whole-repo context.",
    "",
    "1. **IMPLEMENTATION:** Apply the user's goal using microscopic, targeted file diffs. Do not rewrite whole functions or structures unless structurally broken.",
    "",
    "2. **SMART TEST COVERAGE:**",
    "   - **FIRST:** Scan the repository for an existing test file matching this feature surface.",
    `   - **Scoped production surface:** ${featureSurfaceHint}`,
    `   - **Known test candidates from this pack:** ${existingTestHint}`,
    "   - **IF PRESENT:** Review the existing test cases. If the new logic is already covered, **SKIP** creating new tests. If it is not covered, **EXTEND** the existing test file with targeted cases. **DO NOT** duplicate or create a parallel test file.",
    "   - **IF MISSING:** Create a single, native test file (e.g. `*_test.rb`, `*.test.ts`) that strictly targets the new paths or modified logic.",
    "",
    "3. **LOCAL VERIFICATION:** Before declaring success, you must run the local verification harness via:",
    `   \`${primaryVerify}\``,
    "   - Fix all failures before finishing. This command is synced to **MSGF → Run Scripts**; the operator will re-run it without regenerating this prompt.",
    "",
    "4. **OUTPUT SUMMARY:** Conclude your execution with a clear Markdown table mapping exactly:",
    "",
    "| File | Change | Test spec executed | Pass/Fail |",
    "|------|--------|-------------------|-----------|",
    "| _(path)_ | _(brief)_ | _(command or example)_ | _(status)_ |",
    "",
    "Include every modified file, every test file touched or intentionally skipped (with reason), and the final terminal status of the verify command.",
    "",
  ];
}
